# data-raw/glasgow_embeddings.R

# NOTE: This script requires the `wordfeatures` package to be loaded
# or `devtools::load_all()` to be run first. Set the provider below and make
# sure the matching API key environment variable is available before running.

provider <- "openai"
openai_model <- "text-embedding-3-large"
google_model <- "embedding-001"
batch_size <- 100
pause_seconds <- 1

# Load necessary function and data
# Assuming devtools::load_all() or library(wordfeatures) has been run
if (!exists("word_embeddings") || !exists("glasgow_norms")) {
  if (requireNamespace("devtools", quietly = TRUE)) {
    message("Loading package 'wordfeatures' using devtools::load_all()")
    devtools::load_all()
  } else {
    stop("Please load the 'wordfeatures' package first (e.g., using library(wordfeatures) or devtools::load_all()).")
  }
}

# Ensure glasgow_norms data is loaded (use_data loads it lazily)
data("glasgow_norms", package = "wordfeatures", envir = environment())

# Check if glasgow_norms was loaded successfully
if (!exists("glasgow_norms")) {
  stop("Could not load the 'glasgow_norms' dataset. Make sure it has been generated by running data-raw/glasgow_norms.R")
}

# Extract unique words
unique_words <- unique(glasgow_norms$word)
# Remove any potential NA values if they exist
unique_words <- unique_words[!is.na(unique_words)]

message(paste("Found", length(unique_words), "unique words in glasgow_norms."))

# --- Get Embeddings in Batches ---
if (provider == "openai" && Sys.getenv("OPENAI_API_KEY") == "") {
  stop("OPENAI_API_KEY environment variable is not set.")
}
if (provider == "google" && Sys.getenv("GOOGLE_API_KEY") == "") {
  stop("GOOGLE_API_KEY environment variable is not set.")
}

num_words <- length(unique_words)
num_batches <- ceiling(num_words / batch_size)
selected_model <- if (provider == "openai") openai_model else google_model

message(
  paste(
    "Requesting",
    provider,
    "embeddings in",
    num_batches,
    "batches of size",
    batch_size,
    "using model",
    selected_model,
    "..."
  )
)

# List to store results from each batch
all_embeddings_list <- list()

for (i in 1:num_batches) {
  start_index <- (i - 1) * batch_size + 1
  end_index <- min(i * batch_size, num_words)
  current_batch_words <- unique_words[start_index:end_index]
  
  message(paste("Processing batch", i, "of", num_batches, "(words", start_index, "to", end_index, ")..."))
  
  batch_embeddings <- tryCatch({
    if (provider == "openai") {
      word_embeddings(
        texts = current_batch_words,
        provider = "openai",
        model = openai_model
      )
    } else {
      word_embeddings(
        texts = current_batch_words,
        provider = "google",
        google_model = google_model
      )
    }
  }, error = function(e) {
    warning(paste("Error processing batch", i, ":", e$message, ". Skipping this batch."))
    return(NULL)
  })
  
  # If successful, add results to the list
  if (!is.null(batch_embeddings)) {
    all_embeddings_list <- c(all_embeddings_list, batch_embeddings)
  }
  
  # Add a small delay to avoid hitting rate limits, especially for many batches
  if (i < num_batches) {
    Sys.sleep(pause_seconds)
  }
}

# --- Combine and Save Embeddings ---
if (length(all_embeddings_list) > 0) {
  glasgow_embeddings <- all_embeddings_list
  
  message(
    paste(
      provider,
      "embeddings retrieved successfully for",
      length(glasgow_embeddings),
      "words. Saving to data/glasgow_embeddings.rda..."
    )
  )
  
  if (length(glasgow_embeddings) != num_words && length(all_embeddings_list) > 0) {
      warning("Number of retrieved embeddings (", length(glasgow_embeddings), ") does not match the number of unique words (", num_words, "). Some batches might have failed.")
  }
  
  usethis::use_data(glasgow_embeddings, overwrite = TRUE)
  message("Saved glasgow_embeddings using ", provider, " model ", selected_model, ".")
  
} else {
  message("Failed to retrieve any embeddings. Nothing saved.")
} 
